# result: compile error
continue # expect: test:2: Error at 'continue': Cannot use 'continue' outside of a loop.
